@api_url = https://localhost:4000/api/users


### Get All Users
GET {{api_url}}

### Register User
POST {{api_url}}
Content-Type: application/json

{
    "name": "Jane Doe",
    "password": "p@ss#1234",
    "email": "jane.doe@example.com",
    "roles":["admin"]
}

### Register User
GET {{api_url}}

### Login User
POST {{api_url}}/signin
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "p@ss#1234"
}