@api_url = https://localhost:4000/api/users


### Get All Users
GET {{api_url}}
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczODE1MjcwNCwiZXhwIjoxNzM4MTUzMDA0LCJjbGFpbXMiOnsibmFtZSI6IkphbmUgRG9lIiwiZW1haWwiOiJqYW5lLmRvZUBlbWFpbC5jb20iLCJwaG90byI6ImphbmUuanBnIiwicm9sZXMiOlsiYWRtaW4iXSwiYWN0aXZlIjp0cnVlfSwic3ViIjoiamFuZS5kb2VAZW1haWwuY29tIn0.d1n_Js8P183AXq83sCr5ng6tBaj_9_toEKByZbGc-Io

### Register User
POST {{api_url}}
Content-Type: application/json

{
    "name": "John Doe",
    "password": "p@ss#1234",
    "email": "jane.doe@example.com"
    
}


### Register Admin User
POST {{api_url}}
Content-Type: application/json

{
    "name": "Jane Doe",
    "password": "p@ss#1234",
    "photo":"jane.jpg",
    "email": "jane.doe@email.com",
    "roles":["admin"]
}

###  Registering Admin User
POST {{api_url}}
Content-Type: application/json

{
    "name": "Vivek",
    "password": "p@ss#1234",
    "photo":"vivek.jpg",
    "email": "vivek@email.com",
    "roles":["author","Admin"]
}


### Register New User
POST {{api_url}}
Content-Type: application/json

{
"name": "Vivek Dutta Mishra",
    "password": "p@ss#1234",
    "photo":"vivek.jpg",
    "email": "vivek@gmail.com",
    "roles":["author","editor"]
}

### Login User
POST {{api_url}}/signin
Content-Type: application/json

{
    "password": "p@ss#1234",
    "email": "vivek@gmail.com"
}

### GET all users
GET {{api_url}}

### Login User
POST {{api_url}}/signin
Content-Type: application/json

{
    "email": "jane.doe@email.com",
    "password": "p@ss#1234"
}


### Find Current User Info witout header
GET {{api_url}}/current


### Find Current User Info with valid token
GET {{api_url}}/current
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczODE1MTk1MSwiZXhwIjoxNzM4MTUyMjUxLCJjbGFpbXMiOnsibmFtZSI6IlZpdmVrIER1dHRhIE1pc2hyYSIsImVtYWlsIjoidml2ZWtAZ21haWwuY29tIiwicGhvdG8iOiJ2aXZlay5qcGciLCJyb2xlcyI6WyJhdXRob3IiLCJlZGl0b3IiXSwiYWN0aXZlIjp0cnVlfSwic3ViIjoidml2ZWtAZ21haWwuY29tIn0.EYu0HKQYevUxTrrDLvlBNqXH1ceUIwArH4fCgUt05uk

### Find Current User Info with invalidvalid token
GET {{api_url}}/current
Authorization: BEARER eyJhbXXXGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsidXNlciJdLCJhY3RpdmUiOnRydWUsImlhdCI6MTczODE0NzEwMn0.Z08mNFe2rRHo19gPRAtTaquoYItaiaGd0HFapQAS2cQ 




### Activate User jane.doe@example.com
PATCH {{api_url}}/jane.doe@email.com/activate
Content-Type: application/json

{
    "active":true
}